### ISSUE TITLE
Client should handle 502 errors

### ISSUE THREAD

**Issue by skairunner** [Unleash/unleash-client-rust#37] opened 2022-06-14 08:30 UTC
### Describe the bug

The unleash server can return the following error when polling for features (`poll_for_update()`): 

```
\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n
```

The client currently naively tries to convert the returned body into json, fails, then dumps the error and proceeds as if an unrecoverable error happened, by not updating the features until the next poll interval/

This should be easily fixable by inspecting the response's status code and reacting to a 502, before converting it into a json.

### Steps to reproduce the bug

Unfortunately I am unsure as to how to reproduce the error, as it may have something to do with specific server configurations or even the environment. However, it might be possible to mock the response from the server.

### Expected behavior

Unleash client should probably retry the request as said by the server.

### Unleash version

Client: 0.6.1 alpha
Server: 3.17.6

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by andreas-unleash** [comment] 2022-06-14 11:09
Hey, thank you for bringing this to our attention. We will raise it internally and get back to you with a response from the team. 

In the meantime, can you provide us with some additional information to help reproduce it:  
- Server configuration
- Environmant configuration

**Comment by skairunner** [comment] 2022-06-15 09:30
Upon investigation, the conditions for this error being returned does indeed depend on non-Unleash software: The Unleash server was hosted on a Kubernetes cluster behind a Google load balancer. The server was being CPU-throttled and the load balancer returned the 502 message.

Still, it might be good to have some better handling of server errors.

**Comment by thomasheartman** [comment] 2022-06-16 12:09
Hey, @skairunner 👋🏼 

Thanks again for raising this! Let me just make sure I get this right:

- When the client receives a 502 response, it logs an error, then continues running. It will try fetching toggles again at the next interval.
- When it receives a 502, you'd like/expect it to retry the toggle request after the specified interval.

Are those points correct?

We've talked briefly about this internally, and I think the reason it works the way it does is intentional. There's not much the SDK can do if it receives an error response, and it'll try again after the specified refresh interval anyway. In cases where you need to get updates immediately, you're probably best off bumping up the refresh rate.

Does that sound reasonable to you?

> Still, it might be good to have some better handling of server errors.

That's a fair point! What would you classify as "better handling" in this case? What would you expect? ☺️

**Comment by thomasheartman** [comment] 2022-06-17 09:57
Got it! In that case I'll close this for now ☺️ I think getting some more information would be good though; maybe it's something that can be worked into #36?

**Closed by thomasheartman** 2022-06-17 09:57 UTC
Labels: bug
